---
  # APP_DOCS: 'docs'
  SECRET_KEY: 'f593300815283452ffe458531bd57266c39f1'
  MAX_CONTENT_LENGTH: 16777216
  CAS_SERVER: "https://cas.byu.edu"
  CAS_AFTER_LOGIN: 'cas_login'
  # SESSION_TYPE: 'filesystem'
  # FLASK_ADMIN_SWATCH: 'cerulean'
  # SELECTION_ALGORITHM: pairall()
  # PAIRS_BEING_PROCESSED_PATH: 'crowdsorting/app_resources/pairs_being_processed/pairsBeingProcessed.pkl'
  # EMAIL_DICT_PATH: 'crowdsorting/app_resources/pairs_being_processed/email_dict.pkl'
  SUBDIRECTORY_ROOT: 'crowd-sorting'